repos:
    - repo: https://github.com/python-poetry/poetry
      rev: "1.3.0" # add version here
      hooks:
          - id: poetry-export
            args: ["-f", "requirements.txt", "-o", "requirements.txt"]
            verbose: true
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: "" # Use the sha / tag you want to point at
      hooks:
          - id: autopep8
