repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'  # add version here
    hooks:
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
