# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

# 平台机器人的配置信息，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。

[bot_aiocqhttp]
qq_account = 1234567 # 机器人 QQ 号（部署 QQ 机器人（使用 onebot11（aiocqhttp） 部署时）使用）
qq_enable_listening_self_message = false # 使用 onebot 协议时，是否启用自身消息监听。
qq_disable_temp_session = true # 使用 onebot 协议时，是否启用临时会话。
qq_allow_approve_friend = false # 使用 onebot 协议时，是否自动同意好友请求。
qq_allow_approve_group_invite = false # 使用 onebot 协议时，是否自动同意群邀请。
enable = false # 是否启用。
qq_frame_type = "mirai" # Aiocqhttp 对接的 onebot 协议的框架类型。
