# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

# 平台机器人的密钥信息配置，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。

[bot_kook_secret]
kook_token = "<Replace me with a str value>" # Kook 机器人的 Token。
