# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

# 密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。

[secret]
proxy = "<Replace me with a str value>" # 代理地址。
check_access_key_id = "<Replace me with a str value>" # 阿里云内容安全服务的 Access Key ID。
check_access_key_secret = "<Replace me with a str value>" # 阿里云内容安全服务的 Access Key Secret。
db_path = "<Replace me with a str value>" # 数据库连接字符串，请使用 SQLAlchemy 支持的数据库连接字符串格式。
ff3_key = "0FCB4F858FE077B40BE605EFDEDB8817" # 用于加密敏感信息的密钥（使用 ff3 算法进行加密，部分场景可能会使用到）。
ff3_tweak = "1C79F5F79A8282" # 用于加密敏感信息的密钥偏移量。
openai_api_key = "<Replace me with a str value>" # openai 的 API Key。（用于ask模块，人工智能对话）
exchange_rate_api_key = "" # exchange_rate 的 API Key。（用于exchange_rate模块，计算汇率用）
wolfram_alpha_appid = "<Replace me with a str value>" # wolframalpha 的 AppID。（用于wolframalpha模块，查询 WolframAlpha 数据）
diving_fish_developer_token = "<Replace me with a str value>" # diving fish 查分器的开发者 Token。（用于maimai模块）
curseforge_api_key = "<Replace me with a str value>" # curseforge 的 API Key。（用于mod_dl模块）
ncmusic_api = "<Replace me with a str value>" # ncmusic 的 API地址。（用于ncmusic模块，网易云音乐查询）
osu_api_key = "<Replace me with a str value>" # osu! 的 API Key。（用于osu模块，查询 osu! 数据）
