default_locale = "en_us" # 默认的对话语言环境。
config_version = 0 # 配置版本号，将会随功能更新自增，一般情况请勿修改。
initialized = true
# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

# 一些基础的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。

[config]
enable_dirty_check = false # 是否启用文字过滤检测，需要配置阿里云内容安全服务的 Access Key ID 与 Access Key Secret。
enable_urlmanager = false # 是否启用 URLManager，用于 URL 跳板用。（声明此 URL 非官方链接等）
ignored_sender = ["QQ|2854196310"] # 无视的发送者列表，匹配到此列表中的发送者将会被忽略。
issue_url = "https://github.com/Teahouse-Studios/bot/issues/new/choose" # 问题反馈地址。
enable_analytics = false # 是否启用内置的统计功能。
qq_typing_emoji = "181" # 使用 QQ 相关协议端时，正在处理消息时向消息挂上的回应 emoji id，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api/openapi/emoji/model.html#Emoji
api_port = 5000 # API 服务的端口号。
enable_petal = false # 是否启用花瓣功能。
enable_rickroll = true # 当文字过滤检测失败时，是否 rickroll 对象。
rickroll_msg = "<Replace me with a str value>" # 文字过滤检测失败时的rickroll消息。
enable_joke = false # 是否启用玩笑。
joke_type = "<Replace me with a str value>"
shuffle_rate = 0.1 # 玩笑的随机发生率。
unloaded_modules = []
debug = false # 是否启用调试模式，启用后会输出更多的日志信息。
report_targets = [] # 反馈目标列表，此处填写的值将会被识别为反馈目标。（如：在机器人执行命令出错时，机器人将会把报错信息发送至对象）
tos_warning_counts = 5 # 违反 Tos 时的警告次数。
base_superuser = ["QQ|2596322644"] # 机器人的基础超级用户列表，此处填写的值将会在机器人启动时被加载进入数据库。
bug_report_url = "https://s.wd-ljt.com/botreportbug" # bug 反馈地址。
timezone_offset = "+8" # 机器人的默认时区偏移量。
no_confirm = false # 是否无需发送者确认消息再执行命令。
confirm_command = ["是", "对", "對", "yes", "Yes", "YES", "y", "Y"] # 确认命令的关键词，此处填写的值将会被识别为确认命令。
command_prefix = ["~", "～"] # 命令前缀，此处填写的值将会被识别为命令前缀。
enable_tos = true # 是否启用内置的 Tos 检查规则。
tos_temp_ban_time = 300 # 违反 Tos 时的临时封禁时间。
qq_limited_emoji = "10060" # 使用 QQ 相关协议端时，消息处理失败时向消息挂上的回应 emoji，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api/openapi/emoji/model.html#Emoji
allow_request_private_ip = false # 是否允许机器人请求本地私有 IP 地址。（防止可能的信息泄露）
enable_get_petal = false # 是否允许获取花瓣。
gained_petal_limit = 0 # 单日获取花瓣上限。
lost_petal_limit = 0 # 单日丢失花瓣上限。
use_secrets_random = false # 是否使用 secrets 模块的随机数生成器。
enable_langsmith = "<Replace me>"
langsmith_endpoint = "<Replace me>"
langsmith_project = "<Replace me>"
langsmith_api_key = "<Replace me>"
coin_limit = 10000 # coin 模块可抛硬币的上限。
coin_faceup_rate = 4997 # coin 模块抛硬币时正面的概率。
coin_facedown_rate = 4997 # coin 模块抛硬币时反面的概率。
help_page_url = "https://bot.teahouse.team/wiki/${module}" # 模块帮助地址。
help_url = "https://bot.teahouse.team" # 帮助地址。
donate_url = "http://afdian.com/a/teahouse" # 捐赠地址。
allow_reload_base = false # 是否允许重载基础模块。
enable_eval = false # 是否启用 eval 模块。
enable_commit_url = true # 是否在展示版本信息时显示 commit URL。
locale_url = "https://www.crowdin.com/project/akari-bot" # 本地化项目地址。
dice_limit = 100 # dice 模块的一次摇动最多的骰子数量。
dice_output_count = 50 # dice 模块的输出的最多数据量。
dice_output_len = 200 # dice 模块的输出的最大长度。
dice_roll_limit = 10 # dice 模块一次命令最多的摇动次数。
dice_detail_count = 5 # dice 模块的 n 次投掷的骰子的总量超过该值时将不再显示详细信息。
dice_count_limit = 10 # dice 模块的骰子表达式最多的项数。
ncmusic_enable_card = false # ncmusic 模块是否启用卡片消息。
wiki_whitelist_url = "<Replace me with a str value>" # wiki 模块白名单申请地址。
wordle_disable_image = false # wordle 模块是否禁用图片。
slower_schedule = false # 是否启用更慢的计划任务调度器。（减少请求压力用）
