# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

# 平台机器人的配置信息，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。

[bot_matrix]
enable = false # 是否启用。
matrix_homeserver = "<Replace me with a str value>" # matrix 机器人的 homeserver。
matrix_user = "<Replace me with a str value>" # matrix 机器人的用户 ID。
