# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_matrix]
# 平台协议端的配置信息，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # 是否启用平台。
matrix_homeserver = "<Replace me with str value>" # matrix 机器人的家服务器。
matrix_user = "<Replace me with str value>" # matrix 机器人的完全限定用户 ID。

[bot_matrix_secret]
# 平台协议端的密钥配置信息，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
matrix_device_id = "<Replace me with str value>" # Matrix 机器人设备 ID。
matrix_device_name = "<Replace me with str value>" # matrix 机器人的设备名称。
matrix_token = "<Replace me with str value>" # Matrix 机器人 Token。
matrix_megolm_backup_passphrase = "<Replace me with str value>" # Matrix 机器人的 Megolm 备份密码短语。
