# https://toml.io/en/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_discord_secret]
# 平台协议端的密钥配置信息，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
discord_token = "<Replace me with str value>" # Discord 机器人 Token。

[bot_discord]
# 平台协议端的配置信息，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # 是否启用平台。
