name: Update Dependencies

on:
    workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install poetry
        run: |
          pip install poetry

      - name: Update dependencies
        run: |
          poetry update

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update dependencies"
          git push

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update dependencies"
          branch: update-dependencies
          title: "Update dependencies"
          body: "This pull request updates the dependencies based on the latest versions from the poetry repository."
